CREATE DATABASE IF NOT EXISTS cleanswift;
USE cleanswift;

CREATE TABLE IF NOT EXISTS Customer (
    CustomerID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL UNIQUE,
    Phone VARCHAR(14) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Address VARCHAR(255) NOT NULL
);

CREATE TABLE Cleaner (
    CleanerID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL UNIQUE,
    AssignedArea VARCHAR(100) NOT NULL,
    Ratings FLOAT
);

CREATE TABLE ServicePackage (
    PackageID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL UNIQUE,
    Description VARCHAR(255) NOT NULL,
    Price FLOAT NOT NULL
);

CREATE TABLE Booking (
    BookingID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CustomerID INT,
    PackageID INT,
    Date DATE NOT NULL,
    Status VARCHAR(15) NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
    FOREIGN KEY (PackageID) REFERENCES ServicePackage(PackageID)
);

CREATE TABLE Payment (
    PaymentID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    BookingID INT,
    Amount FLOAT NOT NULL,
    Date DATE NOT NULL,
    Status VARCHAR(15),
    FOREIGN KEY (BookingID) REFERENCES Booking(BookingID)
);

CREATE TABLE Feedback (
    FeedbackID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CustomerID INT,
    CleanerID INT,
    Rating FLOAT,
    Comments VARCHAR(255),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
    FOREIGN KEY (CleanerID) REFERENCES Cleaner(CleanerID)
);
